config/routes.rb
Rails.application.routes.draw do

  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match 'company/register', as: :register, via: [:get, :post]

  match 'company/info', via: [:get, :post, :patch, :put], as: :company_info

  get 'sessions/new', as: :login

  post 'sessions/create', as: :create_login

  match 'sessions/logout', as: :logout, via: [:get, :delete]

  root 'company#info'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}, uniqueness: true
  has_one :info, class_name: CompanyInfo
end

app/controllers/company_controller.rb
# encoding: utf-8
class CompanyController < ApplicationController
  before_action :request_login!, only: :info
  def register
    @company ||= Company.new
    if params[:company] && params[:agreecheck]
      @company = Company.new params[:company].slice(:name,:email, :password, :password_confirmation).to_hash
      if @company.save
        session[:company_id] = @company.id
        redirect_to company_info_path
      end
    end
  end

  def info
    @info = current_company.info || current_company.build_info
    attrs = info_params
    if attrs && (@info.new_record? || @info.license_file.blank? || @info.agency_terms_file.blank)
      if session[:temp_id]
        @temp = InfoTempfile.find session[:temp_id]
      else
        @temp = InfoTempfile.new
      end
      @temp.license_file = attrs[:license_file] || @temp.license_file
      @temp.agency_terms_file = attrs[:agency_terms_file] || @temp.agency_terms_file
      @temp.save
      session[:temp_id] = @temp.id
      @info.license_file = @temp.license_file
      @info.agency_terms_file = @temp.agency_terms_file
    end
    if attrs && @info.pending?
      attrs.delete :license_file if attrs[:license_file].blank?
      attrs.delete :agency_terms_file if attrs[:agency_terms_file].blank?
      @info.update_attributes attrs
    end
  end

  def info_params
    params.require(:company_info).permit(CompanyInfo.column_names.select{|s| s != 'status'}) if params[:company_info]
  end
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/views/company/_info_form.html.slim
= render_error_messages info
legend
  | Tell us  your business
  - unless info.new_record?
    - if params[:flag]
      = link_to 'Show', url_for(flag: nil), class: 'btn btn-default pull-right'
    - elsif (controller_name == 'company' && info.pending?) || controller_name != 'company'
      = link_to 'Edit', url_for(flag: :edit), class: 'btn btn-success pull-right'
.form-group
  = f.label :license_no do
    addr.required *
    | Business License No.
  = f.text_field :license_no, default_field_options.merge(class: 'form-control')
.form-group
  = f.label :license_file do
    addr.required *
    | Upload the scan copy of your business license
  = f.file_field :license_file, default_field_options.merge(class: 'form-control', accept: 'image/*')
  - if info.license_file.present?
    = link_to info.license_file.url, target: :_blank do
      = image_tag info.license_file.url, width: 200, height: 200
.form-group
  = f.label :company_profile
  = f.text_area :company_profile, default_field_options.merge(class: 'form-control')
.form-group
  = f.label :street_address1 do
    addr.required *
    | Address Street address 1
  = f.text_field :street_address1, default_field_options.merge(class: 'form-control')
.form-group
  = f.label :street_address2 do
    |  Address Street address 2
  = f.text_field :street_address2, default_field_options.merge(class: 'form-control')
.row.form-group
  .col-sm-6
    = f.label :city do
      addr.required *
      | City
    = f.text_field :city, default_field_options.merge(class: 'form-control')
  .col-sm-6
    = f.label :state do
      addr.required *
      | state
    = f.text_field :state, default_field_options.merge(class: 'form-control')
.form-group.row
  .col-sm-6
    = f.label :zip_code do
      addr.required *
      | ZIP / Postal code
    = f.text_field :zip_code, default_field_options.merge(class: 'form-control')
  .col-sm-6
    = f.label :country do
      addr.required *
      | Country
    = f.select :country, Rails.application.secrets.countries.to_a.map{|s| s.reverse},{}, default_field_options.merge(class: 'form-control')
.form-group
  = f.label :tel1 do
    addr.required *
    |  Tel
  .row.custom-input-div
    = f.text_field :tel1, default_field_options.merge( class: 'inline')
    | &nbsp;-&nbsp;
    = f.text_field :tel2, default_field_options.merge( class: 'inline')
    | &nbsp;&nbsp;ext:&nbsp;
    = f.text_field :tel_ext, default_field_options.merge( class: 'inline', placeholder: 'Optional')
.form-group
  = f.label :fax1 do
    addr.required *
    |  Fax
  .row.custom-input-div
    = f.text_field :fax1, default_field_options.merge( class: 'inline')
    | &nbsp;-&nbsp;
    = f.text_field :fax2, default_field_options.merge( class: 'inline')
    | &nbsp;&nbsp;ext:&nbsp;
    = f.text_field :fax_ext, default_field_options.merge( class: 'inline', placeholder: 'Optional')
.form-group
  = f.label :company_website
  = f.text_field :company_website, default_field_options.merge(class: 'form-control')
.form-group
  = f.label :date_of_incorporation do
    addr.required *
    | Date of incorporation. e.g. 2014-12-02
  = f.text_field :date_of_incorporation, default_field_options.merge(class: 'form-control')
.form-group
  = f.label :brand_ownership do
    addr.required *
    | Brand ownership
  .row.custom-input-div
    - Rails.application.secrets.brand_ownership.each do |bs|
      label.radio-inline
        = f.radio_button :brand_ownership, bs, default_field_options
        = bs
.form-group
  = f.label :product_category
  = f.text_area :product_category, default_field_options.merge(class: 'form-control')
.form-group
  = f.label :brand_list do
    addr.required *
    | Brand list
  = f.text_area :brand_list, default_field_options.merge(class: 'form-control')
.form-group
  = f.label :safes_achieved_in_2014 do
    addr.required *
    | Sales achieved in 2014 (USD)
  = f.text_field :safes_achieved_in_2014, default_field_options.merge(class: 'form-control')
.form-group
  = f.label :address_of_flagship_store do
    | Any retail outlet? Address of flagship store
  = f.text_field :address_of_flagship_store, default_field_options.merge(class: 'form-control')
.form-group
  = f.label :contact_person do
    addr.required *
    | Contact person
  = f.text_field :contact_person, default_field_options.merge(class: 'form-control')
.form-group
  = f.label :language
  .row.custom-input-div
    = f.label :mother_tongue, class: 'col-sm-2'
    = f.text_field :mother_tongue, default_field_options.merge( class: 'form-control col-sm-10')

  .row.custom-input-div
    = f.label :language_en_level, 'English', class: 'col-sm-2'
    - Rails.application.secrets.language_level.each do |lv|
      label.radio-inline
        = f.radio_button :language_en_level, lv, default_field_options
        = lv

  .row.custom-input-div
    = f.label :language_zh_level, 'Chinese', class: 'col-sm-2'
    - Rails.application.secrets.language_level.each do |lv|
      label.radio-inline
        = f.radio_button :language_zh_level, lv, default_field_options
        = lv
.row.form-group
  .col-sm-6
    = f.label :office_tel do
      addr.required *
      | Office Tel
    = f.text_field :office_tel, default_field_options.merge(class: 'form-control')
  .col-sm-6
    = f.label :wechat_account do
      | Wechat account
    = f.text_field :wechat_account, default_field_options.merge(class: 'form-control')
.row.form-group
  .col-sm-6
    = f.label :cell_phone do
      addr.required *
      | Cell phone
    = f.text_field :cell_phone, default_field_options.merge(class: 'form-control')
  .col-sm-6
    = f.label :skype_account_skype  do
      | Skype account
    = f.text_field :skype_account_skype, default_field_options.merge(class: 'form-control')
.row.form-group
  .col-sm-6
    = f.label :email do
      addr.required *
      | Email
    = f.text_field :email, default_field_options.merge(class: 'form-control')
  .col-sm-6
    = f.label :qq do
      | QQ
    = f.text_field :qq, default_field_options.merge(class: 'form-control')
.form-group
  addr.text-primary Note:
  br
  p Contact persons must be able to communicate in Chinese or English.
legend China agency information
.form-group
  = f.label :china_agent_company do
    | Appointed agents in China ( including Taiwan\Hongkong\Macau )
  .radio
    label
      = f.radio_button :china_agent_company, true, default_field_options
      | Yes, company name
      = f.text_field :china_agent_company_name, default_field_options.merge( class: 'inline')
  .radio
    label
      = f.radio_button :china_agent_company, false, default_field_options
      | No
.form-group
  = f.label :wish_find_agent_in_china do
    | Wish to find an agent in China (including Taiwan\Hongkong\Macau ) ?
  .row.custom-input-div
    label.radio-inline
      = f.radio_button :wish_find_agent_in_china, true, default_field_options
      | Yes
    label.radio-inline
      = f.radio_button :wish_find_agent_in_china, false, default_field_options
      | No
.form-group
  = f.label :agency_terms_file do
    | Agency terms ( please upload detailed document as attachment )
  = f.file_field :agency_terms_file, default_field_options.merge(class: 'form-control', accept: '.doc, .docx, .txt, .pdf, .xls, .xlsx, .jpg')
  - if info.agency_terms_file.present?
    - if info.agency_terms_file.file.extension.downcase == 'jpg'
      = link_to info.agency_terms_file.url do
        = image_tag info.agency_terms_file.url, width: 200, height: 200
    - else
      = link_to 'Download', info.agency_terms_file.url
legend Operating information
.form-group
  = f.label :online_shop_website do
    | Online shop website
  = f.text_field :online_shop_website, default_field_options.merge(class: 'form-control')
.form-group
  = f.label :sales_channel do
    | Existing online sales channel
  .row.custom-input-div
    label.radio-inline
      = f.radio_button :sales_channel, 'Self-own website', default_field_options
      | Self-own website'
    label.radio-inline
      = f.radio_button :sales_channel, 'Third party e-business platform', default_field_options
      | Third party e-business platform
.form-group
  = f.label :turnover_of_online_safes_in_2014 do
    | Turnover of online sales in 2014 (USD)
  = f.text_field :turnover_of_online_safes_in_2014, default_field_options.merge(class: 'form-control')
.row.form-group
  .col-sm-6
    = f.label :number_of_operation_team_members
    = f.text_field :number_of_operation_team_members, default_field_options.merge(class: 'form-control')
  .col-sm-6
    = f.label :number_of_customer_service_team_members
    = f.text_field :number_of_customer_service_team_members, default_field_options.merge(class: 'form-control')
.row.form-group
  .col-sm-6
    = f.label :number_of_technical_team_members
    = f.text_field :number_of_technical_team_members, default_field_options.merge(class: 'form-control')
  .col-sm-6
    = f.label :warehouse_size, 'Warehouse size (M3)'
    = f.text_field :warehouse_size, default_field_options.merge(class: 'form-control')
.row.form-group
  .col-sm-6
    = f.label :bank_account do
      addr.required *
      | Bank account
    = f.text_field :bank_account, default_field_options.merge(class: 'form-control')
  .col-sm-6
    = f.label :bank_name do
      addr.required *
      | Band name
    = f.text_field :bank_name, default_field_options.merge(class: 'form-control')
.row.form-group
  .col-sm-6
    = f.label :beneficiary do
      addr.required *
      | Beneficiary
    = f.text_field :beneficiary, default_field_options.merge(class: 'form-control')
  .col-sm-6
    = f.label :swift_no do
      addr.required *
      | Swift No.
    = f.text_field :swift_no, default_field_options.merge(class: 'form-control')
.form-group
  = f.label :payment_terms_with_ecat do
    | Payment terms with ecat
  .row.custom-input-div
    label.radio-inline
      = f.radio_button :payment_terms_with_ecat, 'On 5th day of each month', default_field_options
      | On 5th day of each month
    label.radio-inline
      = f.radio_button :payment_terms_with_ecat, 'Every settlement of RMB25,000', default_field_options
      | Every settlement of RMB25,000
.form-group
  p
    addr.text-primary Note:
    | Minimum bank charge for each transfer: USD50.
    br
    addr.text-muted Payment rate: 2%
legend Logistics
.form-group
  = f.label :product_inventory_location do
    | Product inventory location
  = f.text_field :product_inventory_location, default_field_options.merge( class: 'form-control')
.form-group
  = f.label :logistics_mode do
    |   Logistics mode
  .row.custom-input-div
    label.radio-inline
      = f.radio_button :logistics_mode, 'B2C', default_field_options
      | B2C
    label.radio-inline
      = f.radio_button :logistics_mode, 'BBC', default_field_options
      | BBC
- if can_edit?
  = f.submit "Submit", class: 'btn btn-default'

app/views/company/info.html.slim
.container
  = link_to "Logout", logout_path
  = form_for @info, url: company_info_path(params.slice(:flag)), html:{class: 'custom-form info-form'} do |f|
    fieldset
      - unless @info.new_record?
        h4 class="#{@info.successful? ? "text-success" : "text-danger"}"
          | Check Status:&nbsp;
          = @info.check_status
      = render "info_form", f: f, info: @info, default_field_options: {disabled: !can_edit?}

app/views/company/register.html.slim
.container.container-form
  = semantic_form_for @company, url: register_path, html:{class: 'custom-form small-form'} do |f|
    fieldset
      legend
        | Start a business account
        = link_to "Login", login_path, class: 'btn btn-success pull-right'
      - if params[:company].present? && params[:agreecheck].blank?
        p.text-danger Please read and accepted the User Agreement.
      = render_error_messages @company
      .form-group
        = f.label :name, "Company name"
        = f.text_field :name,class: 'form-control'
      .form-group
        = f.label :email
        = f.text_field :email,class: 'form-control'
      .form-group
        = f.label :password
        = f.password_field :password, class: 'form-control', require: true
      .form-group
        = f.label :password_confirmation
        = f.password_field :password_confirmation, class: 'form-control', require: true
      .checkbox
        label
          input type='checkbox' name='agreecheck'
          | I have read and accepted the User Agreement.
      div style="height: 200px;overflow:auto;border:1px solid #ddd;padding: 3px;margin-bottom: 10px"
        = render_agreement_text
      .form-group.clearfix
        = f.submit "Submit", class: 'btn btn-default'